version: "3"
services:
  certbot-auto:
    build: .
    environment:
      - EMAIL=test@domain.com
      - DNS_PROVIDER=cloudflare
      - DOMAIN=my-domain.com
      - STAGING=true
      - EXTRA_ARGS=
    volumes:
      - "./dns-creds:/etc/dns-creds"
      - "./letsencrypt:/etc/letsencrypt"
    restart: unless-stopped
